# Project-wide Gradle settings.
android.useAndroidX=true
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
newArchEnabled=true
hermesEnabled=true
edgeToEdgeEnabled=false

# Android Upload Key Configuration
PLANETCINEMA_UPLOAD_STORE_FILE=planetcinema-upload-key.keystore
PLANETCINEMA_UPLOAD_KEY_ALIAS=planetcinema-key-alias
PLANETCINEMA_UPLOAD_STORE_PASSWORD=planetcinema123
PLANETCINEMA_UPLOAD_KEY_PASSWORD=planetcinema123
